### PR TITLE
Utilise dateutil for parsing date

### PR DESCRIPTION
**Pull request by soraxas**
Hi! First of all, thanks for such a great tool for syncing against Google Calendar, it will be very helpful for using taskwarrior in mobile :)

This PR is very simple, which convert your handcrafted datetime parser into utilising `dateutil.parser.parse` to do its job as to avoid reinventing the wheel. While your code in `parse_datetime(...)` works in the cases that you layout in the function doc, it broke when i used:
```
Traceback (most recent call last):
  File "/home/iamsomeone/.local/bin/tw_gcal_sync", line 71, in <module>
    main()
  File "/home/iamsomeone/.pyenv/versions/3.6.5/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/iamsomeone/.pyenv/versions/3.6.5/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/iamsomeone/.pyenv/versions/3.6.5/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/iamsomeone/.pyenv/versions/3.6.5/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/iamsomeone/.local/bin/tw_gcal_sync", line 63, in main
    aggregator.register_items(gcal_items, "gcal")
  File "/home/iamsomeone/.local/lib/python3.6/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 185, in register_items
    item_converted = convert_fun(item)
  File "/home/iamsomeone/.local/lib/python3.6/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 501, in convert_gcal_to_tw
    tw_item["due"] = GCalSide.get_event_time(gcal_item, t="end")
  File "/home/iamsomeone/.local/lib/python3.6/site-packages/taskw_gcal_sync/GCalSide.py", line 235, in get_event_time
    dt = GCalSide.parse_datetime(item[t][GCalSide.get_date_key(item[t])])
  File "/home/iamsomeone/.local/lib/python3.6/site-packages/taskw_gcal_sync/GCalSide.py", line 295, in parse_datetime
    assert dot_pos != -1, "Invalid format - {}".format(dt)
AssertionError: Invalid format - 2019-12-04T20:30:00+11:00
```
It seems like when it was syncing my google calendar entry, it response with a time format `2019-12-04T20:30:00+11:00`. Since in your original code you expect there to be a dot `.` it causes the assertionError. While we can add more cases to overcome this particular cases, I think it's better to utilise a library `dateutil` that is dedicated for parsing.

Right now the function `GCalSide.parse_datetime` is a bit redundant, but I'll leave it for you to decide how to refactor it.

Thanks!

### CODE REVIEW

**Comment by soraxas** [comment]
In addition there were some assertion statement that I fixed along in the commit

**Comment by bergercookie** [comment]
Hi @soraxas ,

Indeed that's one of the most fragile parts of the code.
Thanks for your contribution! Will test it in the next couple of days!

In the meantime, could you take a look at the failing unittests? Take a look at the travis CI dashbord

**Comment by soraxas** [comment]
I fixed one of the failing.
From checking against the original results, it seems like the differences come from your original unit test does not expect timezone information, but the results from `dateutil` contain it.

For the following, first line is the result from original implementation, the second one is from `dateutil.parser.parse`:
```
datetime.datetime(2019, 3, 5, 1, 3, 9)
datetime.datetime(2019, 3, 5, 1, 3, 9, tzinfo=tzutc())
----------
datetime.datetime(2019, 3, 5, 0, 3, 9)
datetime.datetime(2019, 3, 5, 0, 3, 9, tzinfo=tzutc())
----------
datetime.datetime(2019, 3, 4, 5, 0)
datetime.datetime(2019, 3, 4, 5, 0, tzinfo=tzutc())
----------
datetime.datetime(2019, 3, 8, 0, 29, 6, 602000)
datetime.datetime(2019, 3, 8, 0, 29, 6, 602000, tzinfo=tzutc())
----------
datetime.datetime(2019, 3, 4, 5, 0)
datetime.datetime(2019, 3, 4, 5, 0, tzinfo=tzutc())
----------
datetime.datetime(2019, 3, 8, 0, 29, 6, 602000)
datetime.datetime(2019, 3, 8, 0, 29, 6, 602000, tzinfo=tzutc())
----------
datetime.datetime(2019, 3, 9, 0, 0)
datetime.datetime(2019, 3, 9, 0, 0)
----------
datetime.datetime(2019, 3, 16, 16, 1, 32, 486000)
datetime.datetime(2019, 3, 16, 16, 1, 32, 486000, tzinfo=tzutc())
----------
datetime.datetime(2019, 3, 4, 5, 0)
datetime.datetime(2019, 3, 4, 5, 0, tzinfo=tzutc())
----------
datetime.datetime(2019, 3, 8, 0, 29, 6, 602000)
datetime.datetime(2019, 3, 8, 0, 29, 6, 602000, tzinfo=tzutc())
----------
datetime.datetime(2019, 3, 5, 1, 3, 9)
datetime.datetime(2019, 3, 5, 1, 3, 9, tzinfo=tzutc())
----------
datetime.datetime(2019, 3, 5, 0, 3, 9)
datetime.datetime(2019, 3, 5, 0, 3, 9, tzinfo=tzutc())
```

Therefore, to conform to the unittest, the new commit remove the timezone information with `.replace(tzinfo=None)` which fixes one of the source of the failing builds.

**Comment by soraxas** [comment]
There is one more test that is causing the failure. It comes a line from the doctests:
```
>>> GCalSide.parse_datetime('2019-09-04T16:52:42+01:0.000000Z')
datetime.datetime(2019, 9, 4, 17, 52, 42)
```
After some research, this test in fact is a bit inconsistent. According to the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)) and [Time Zone page](https://en.wikipedia.org/wiki/Time_zone#UTC), adding a `Z` directly after the time indicates it's in UTC timezone (i.e. zero offset). However, from the string it looks like at the same time it wants to offset +1 hour as well. I think that's the reason of `dateutil.parse` throwing Exception to indicate unknown time format.

Is that string an actual returned result from google cal? If so, it might be that sometimes they are returning ambiguous result?

**Comment by bergercookie** [comment]
Overall looks good to me.

Some minor changes before we merge it:

* Squash into a single commit - make sure you format the git message in imperative as described in this post: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

* Make this PR to `devel` instead. I've removed the potentially malformed doctest there.

**Comment by bergercookie** [comment]
:+1: 
Thanks! Merging it!

**Pull request merged**
